version: "3.9"

services:

  server:
    container_name: grpc-server
    image: rayzki/mygrpc-server:1.0
    # build:
    #   context: "."
    restart: always
    ports:
      - 30353:50053
    environment:
      TARGET_HOST_SERVER: "[::]:50053"