# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: itnv.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nitnv.proto\x12\x04itnv\"K\n\nAddRequest\x12\x0f\n\x02id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x13\n\x0brequirement\x18\x02 \x01(\t\x12\x10\n\x08testcase\x18\x03 \x01(\tB\x05\n\x03_id\"\x19\n\x0b\x41\x64\x64Response\x12\n\n\x02id\x18\x01 \x01(\x05\"!\n\nGetRequest\x12\x13\n\x0brequirement\x18\x01 \x01(\t\"@\n\x0bGetResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0brequirement\x18\x02 \x01(\t\x12\x10\n\x08testcase\x18\x03 \x01(\t\"0\n\x0cGetResponses\x12 \n\x05items\x18\x01 \x03(\x0b\x32\x11.itnv.GetResponse2\xe4\x01\n\tTestcases\x12\x31\n\nAddElement\x12\x10.itnv.AddRequest\x1a\x11.itnv.AddResponse\x12\x31\n\nGetElement\x12\x10.itnv.GetRequest\x1a\x11.itnv.GetResponse\x12\x33\n\x0bGetElements\x12\x10.itnv.GetRequest\x1a\x12.itnv.GetResponses\x12<\n\x13GetStreamedElements\x12\x10.itnv.GetRequest\x1a\x11.itnv.GetResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'itnv_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ADDREQUEST']._serialized_start=20
  _globals['_ADDREQUEST']._serialized_end=95
  _globals['_ADDRESPONSE']._serialized_start=97
  _globals['_ADDRESPONSE']._serialized_end=122
  _globals['_GETREQUEST']._serialized_start=124
  _globals['_GETREQUEST']._serialized_end=157
  _globals['_GETRESPONSE']._serialized_start=159
  _globals['_GETRESPONSE']._serialized_end=223
  _globals['_GETRESPONSES']._serialized_start=225
  _globals['_GETRESPONSES']._serialized_end=273
  _globals['_TESTCASES']._serialized_start=276
  _globals['_TESTCASES']._serialized_end=504
# @@protoc_insertion_point(module_scope)
