# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import itnv_pb2 as itnv__pb2


class TestcasesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddElement = channel.unary_unary(
                '/itnv.Testcases/AddElement',
                request_serializer=itnv__pb2.AddRequest.SerializeToString,
                response_deserializer=itnv__pb2.AddResponse.FromString,
                )
        self.GetElement = channel.unary_unary(
                '/itnv.Testcases/GetElement',
                request_serializer=itnv__pb2.GetRequest.SerializeToString,
                response_deserializer=itnv__pb2.GetResponse.FromString,
                )
        self.GetElements = channel.unary_unary(
                '/itnv.Testcases/GetElements',
                request_serializer=itnv__pb2.GetRequest.SerializeToString,
                response_deserializer=itnv__pb2.GetResponses.FromString,
                )
        self.GetStreamedElements = channel.unary_stream(
                '/itnv.Testcases/GetStreamedElements',
                request_serializer=itnv__pb2.GetRequest.SerializeToString,
                response_deserializer=itnv__pb2.GetResponse.FromString,
                )


class TestcasesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddElement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetElement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetElements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStreamedElements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestcasesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddElement': grpc.unary_unary_rpc_method_handler(
                    servicer.AddElement,
                    request_deserializer=itnv__pb2.AddRequest.FromString,
                    response_serializer=itnv__pb2.AddResponse.SerializeToString,
            ),
            'GetElement': grpc.unary_unary_rpc_method_handler(
                    servicer.GetElement,
                    request_deserializer=itnv__pb2.GetRequest.FromString,
                    response_serializer=itnv__pb2.GetResponse.SerializeToString,
            ),
            'GetElements': grpc.unary_unary_rpc_method_handler(
                    servicer.GetElements,
                    request_deserializer=itnv__pb2.GetRequest.FromString,
                    response_serializer=itnv__pb2.GetResponses.SerializeToString,
            ),
            'GetStreamedElements': grpc.unary_stream_rpc_method_handler(
                    servicer.GetStreamedElements,
                    request_deserializer=itnv__pb2.GetRequest.FromString,
                    response_serializer=itnv__pb2.GetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'itnv.Testcases', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Testcases(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddElement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/itnv.Testcases/AddElement',
            itnv__pb2.AddRequest.SerializeToString,
            itnv__pb2.AddResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetElement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/itnv.Testcases/GetElement',
            itnv__pb2.GetRequest.SerializeToString,
            itnv__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetElements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/itnv.Testcases/GetElements',
            itnv__pb2.GetRequest.SerializeToString,
            itnv__pb2.GetResponses.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStreamedElements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/itnv.Testcases/GetStreamedElements',
            itnv__pb2.GetRequest.SerializeToString,
            itnv__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
